***************
*** 20,31 ****
  # Foundation, Inc., 59 Temple Place, Suite 330, Boston,
  # MA 02111-1307 USA
  #
  
  include $(TOPDIR)/config.mk
  
  LIB	= lib$(SOC).a
  
- OBJS	= ether.o i2c.o interrupts.o serial.o
  SOBJS	= lowlevel_init.o
  
  all:	.depend $(LIB)
--- 20,33 ----
  # Foundation, Inc., 59 Temple Place, Suite 330, Boston,
  # MA 02111-1307 USA
  #
+ # Modified for u-boot 1.1.3  AT91RM9200 MMC/SD Support 
+ # by Doerte Waldoestl, Ident Technologies GmbH <waldoestl@identtechnologies.de>
  
  include $(TOPDIR)/config.mk
  
  LIB	= lib$(SOC).a
  
+ OBJS	= ether.o i2c.o interrupts.o serial.o mmc.o
  SOBJS	= lowlevel_init.o
  
  all:	.depend $(LIB)
